#!/usr/bin/env zsh
# -*- mode: sh; sh-indentation: 4; indent-tabs-mode: nil; sh-basic-offset: 4; -*-

# Type-agnostic script/function, i.e.: the file can be ran as a +x
# script or as an autoload function

# Run as script? ZSH_SCRIPT is a Zsh 5.3 addition
if [[ $0 != zide || -n $ZSH_SCRIPT ]]; then
    # Handle $0 according to the Zsh Plugin Standard:
    # http://zdharma.org/Zsh-100-Commits-Club/Zsh-Plugin-Standard.html
    0=${${ZERO:-${0:#$ZSH_ARGZERO}}:-${(%):-%N}}
    0=${${(M)0##/*}:-$PWD/$0}

    local ZIDE_DIR=${0:h}
fi

# Set the base and typically useful options
emulate -LR zsh
setopt extended_glob warn_create_global typeset_silent \
        no_short_loops rc_quotes no_auto_pushd

# vim:ft=zsh:sw=4:sts=4:et
